// docs/test-beds/svelte/fixture.svelte
<script lang="ts">
  import { Helper } from './helper';
  import type { Box } from './types';

  export let item: Box;
  export let label: string;
  export let count: number = 0;

  function increment(b: Box): Box {
    count += 1;
    Helper.log(b);
    return b;
  }
</script>

<div>
  <span>{label}: {count}</span>
  <button on:click={() => increment(item)}>+</button>
</div>

// docs/test-beds/jsx/fixture.jsx
// JSX test bed
import { Helper } from './helper';
import React from 'react';

export class Counter extends React.Component {
  render() {
    return <div>{this.props.label}: {this.props.count}</div>;
  }
}

export function App(props) {
  Helper.log(props);
  return <Counter label={props.label} count={props.count} />;
}
